### ISSUE TITLE
Issue when using virtual user in postfix

### ISSUE THREAD

**Issue by olivierb2** [iabsis/roundcube-fetchmail-rc#5]
When postfix uses virtual user, Roundcube fetchmail and redirect mails to the username roundcube instead the user mail.
The best is forwarding mail to defaut roundcube identity mail instead username.

**Comment by gilles-hemmerle** [comment]
Could you please test if it works fine with this news commit.

Thanks.

**Comment by gilles-hemmerle** [comment]
Assume it's ok.
This is closed
